### ISSUE TITLE
Raise error when run `trans`, and I can not launch the desktop entry.

### ISSUE THREAD

**Issue by CZ-Wu** [Freed-Wu/translate-shell#28]
```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wu/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/wu/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wu/anaconda3/lib/python3.9/site-packages/translate_shell/ui/gui.py", line 20, in run
    args.text = check_output(clipper, universal_newlines=True)
  File "/home/wu/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/wu/anaconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/wu/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/wu/anaconda3/lib/python3.9/subprocess.py", line 1691, in _execute_child
    executable = args[0]
IndexError: list index out of range```

**Comment by Freed-Wu** [comment]
What is the output of `trans --print-setting clipper`?

**Comment by Freed-Wu** [comment]
Oh, I guess it should be empty string. I'll fix this bug.
