### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by johnd0e** [Freed-Wu/translate-shell#38]
`trans.exe Free as in Freedom`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\repo\translate-shell\venv\Scripts\trans.exe\__main__.py", line 7, in <module>
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\__main__.py", line 186, in main
    init(args)
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\ui\__init__.py", line 123, in init
    _readline = init_readline()
                ^^^^^^^^^^^^^^^
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\ui\__init__.py", line 47, in init_readline
    atexit.register(readline.write_history_file, HISTORY_FILE)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'translate_shell.external.readline' has no attribute 'write_history_file'. Did you mean: 'read_history_file'?
```
How can I fix it?

**Comment by johnd0e** [comment]
Still not working:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\repo\translate-shell\venv\Scripts\trans.exe\__main__.py", line 7, in <module>
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\__main__.py", line 186, in main
    init(args)
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\ui\__init__.py", line 121, in init
    _readline = init_readline()
                ^^^^^^^^^^^^^^^
  File "D:\repo\translate-shell\venv\Lib\site-packages\translate_shell\ui\__init__.py", line 50, in init_readline
    readline.set_completer_delims(" ")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'translate_shell.external.readline' has no attribute 'set_completer_delims'
```

**Comment by johnd0e** [comment]
Thank you!
